config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'

  devise_for :users
  get 'home/index'

  resources :images
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  namespace 'api' do
    namespace 'v1' do
      post 'auth_user' => 'authentication#authenticate_user'
      post 'sign_up' => 'registration#create'
      resources :images
      resources :products
      resources :points
      resources :items
      resources :orders
      resources :stores
      resources :recycling_stations
    end
  end
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :user
    mount_uploader :picture, PictureUploader
end

app/controllers/api/v1/images_controller.rb
module Api
    module V1
        class ImagesController < ApiApplicationController
            before_action :authenticate_request!

            def index
                images = Image.order('created_at DESC').where user_id: current_user.id
                render json: {status: 'SUCCESS', message: 'Carga de imagenes', data: images}, status: :ok
            end

            def show
                image = Image.find(params[:id])
                render json: {status: 'SUCCESS', message: 'Carga la imagen', data: image}, status: :ok
            end

            def create 
                image = Image.new(image_params)
                if image.save 
                    render json: {status: 'SUCCESS', message: 'imagen guardada', data: image}, status: :ok
                else
                    render json: {status: 'ERROR', message: 'imagen no guardada', data: image}, status: :unprocessable_entity #Error proceso creación
                end
            end

            def destroy 
                image = Image.find(params[:id])
                image.destroy
                render json: {status: 'SUCCESS', message: 'imagen eliminada', data: image}, status: :ok
            end

            def update 
                image = Image.find(params[:id])
                if image.update_attributes(image_params)
                    render json: {status: 'SUCCESS', message: 'imagen editada', data: image}, status: :ok
                else
                    render json: {status: 'ERROR', message: 'imagen no editada', data: image}, status: :unprocessable_entity #Error proceso creación
                end
            end

            private

            def image_params
                params.permit(:description, :picture)
            end

        end
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    before_action :set_image, only: [:show, :edit, :update, :destroy]

    def index
        @images = Image.where user_id: current_user.id
         #ahora hacemos la consulta por medio del id del usuario
    end

    def new
        @image = Image.new
    end

    def create
        @image = current_user.images.new images_params
        @image.save
        redirect_to '/'
    end

    def show
        
    end

    def edit
        
    end

    def update
        @image.update images_params
        redirect_to @image #Redirige a show
    end

    def destroy
        @image.destroy
        redirect_to images_path #Redirige al index
    end

    private

    def images_params
        params.require(:image).permit :description, :picture
    end

    def set_image
        @image = Image.find params[:id]
    end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<div class="form-group">
    <%= form_for @image, :html => {:multipart => true} do |f| %>
        <%= f.label 'Descripción' %> <br>
        <%= f.text_field :description, class: 'form-control' %><br>
        <%= f.label 'Cargar Imagen ' %> <br>
        <%= f.file_field :picture, class: 'form-control-file' %><br>
        <%= f.submit 'Enviar', :class => 'btn btn-primary' %>
    <% end %>
</div>

app/views/images/_image.html.erb
<div class="col-sm-4">
    <figure class="figure">
        <%= image_tag image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>
        <figcaption class="figure-caption">
            <%= image.description %>
            <%= link_to 'Editar', edit_image_path(image) %>
            <%= link_to 'Eliminar', image, method: :delete, data:{ 
                    confirm: 'Esta seguro que desea eliminar esta imagen.'} %>        
        </figcaption> 
    </figure>
</div>

app/views/images/edit.html.erb
<p>Editar imágenes</p>
<%= render 'form'%>

app/views/images/index.html.erb
<h1>Imagesgram</h1>
<div class="row">
    <%= render @images %>
</div>

app/views/images/new.html.erb
<p>INGRESAR IMAGENES</p>
<%= render 'form' %>

app/views/images/show.html.erb
<div class="col-sm-6">
    <%= image_tag @image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>
    <%= @image.description %>
</div>